#!/bin/bash

VERSION=0.10.34
PLATFORM=linux
ARCH=x64
LOCAL_PATH=$PATH
SEARCH="node/bin"
CURRENT_DIR=$(cd $(dirname "$0"); pwd)
#PREFIX="$HOME/node-v$VERSION-$PLATFORM-$ARCH"
VERSIONSTRING="node-v$VERSION-$PLATFORM-$ARCH"
PREFIX="${CURRENT_DIR}/app/Resources/node"

if [ ! -f "$PREFIX/$VERSIONSTRING" ]; then
  if [ -d $PREFIX ]; then
    rm -R $PREFIX
  fi

  mkdir -p "$PREFIX" && curl http://nodejs.org/dist/v$VERSION/node-v$VERSION-$PLATFORM-$ARCH.tar.gz | tar xzvf - --strip-components=1 -C "$PREFIX"
  touch $PREFIX/$VERSIONSTRING
fi

# globally install composer asset handling plugin
composer global require fxp/composer-asset-plugin 1.0.*@dev

if [ "${LOCAL_PATH/$SEARCH}" = "$LOCAL_PATH" ] ; then
  export PATH=$PATH:${CURRENT_DIR}/app/Resources/node/bin
fi

# this fixes our internal ssl cert problems
npm config set registry http://registry.npmjs.org/
npm config set ca ""

# install gulp and modules
npm install --save-dev gulp
npm install --save-dev lodash
npm install --save-dev gulp-autoprefixer
npm install --save-dev gulp-concat
npm install --save-dev gulp-copy
npm install --save-dev gulp-if
npm install --save-dev gulp-jshint
npm install --save-dev gulp-livereload
npm install --save-dev gulp-load-plugins
npm install --save-dev gulp-plumber
npm install --save-dev gulp-stylus
npm install --save-dev gulp-sourcemaps
npm install --save-dev gulp-uglify
npm install --save-dev gulp-uglifycss
npm install --save-dev gulp-util
npm install --save-dev gulp-watch
npm install --save-dev gulp-size
npm install --save-dev gulp-autoprefixer
