#!/bin/bash
LOCAL_PATH=$PATH
SEARCH="node/bin"
CURRENT_DIR=$(cd $(dirname "$0"); pwd)

if [ "${LOCAL_PATH/$SEARCH}" = "$LOCAL_PATH" ] ; then
  export PATH=$PATH:${CURRENT_DIR}/app/Resources/node/bin
fi
node "$@"
